apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0, pipelines.kubeflow.org/pipeline_compilation_time: '2021-06-11T23:29:40.211750',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "My machine learning pipeline",
      "inputs": [{"name": "file_path"}], "name": "My pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.4.0}
spec:
  entrypoint: my-pipeline
  templates:
  - name: my-pipeline
    inputs:
      parameters:
      - {name: file_path}
    dag:
      tasks:
      - name: read-csv
        template: read-csv
        arguments:
          parameters:
          - {name: file_path, value: '{{inputs.parameters.file_path}}'}
  - name: read-csv
    container:
      args: [--i-file, '{{inputs.parameters.file_path}}']
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def read_csv(i_file):
            os.system('export i_file=' + i_file + '; embulk run /home/minikf/embulk/config.yml.liquid')

        import argparse
        _parser = argparse.ArgumentParser(prog='Read csv', description='')
        _parser.add_argument("--i-file", dest="i_file", type=str, required=True, default=argparse.SUPPRESS)
        _parsed_args = vars(_parser.parse_args())

        _outputs = read_csv(**_parsed_args)
      image: python:3.7
    inputs:
      parameters:
      - {name: file_path}
    metadata:
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": ["--i-file", {"inputValue": "i_file"}], "command": ["sh", "-ec",
          "program_path=$(mktemp)\nprintf \"%s\" \"$0\" > \"$program_path\"\npython3
          -u \"$program_path\" \"$@\"\n", "def read_csv(i_file):\n    os.system(''export
          i_file='' + i_file + ''; embulk run /home/minikf/embulk/config.yml.liquid'')\n\nimport
          argparse\n_parser = argparse.ArgumentParser(prog=''Read csv'', description='''')\n_parser.add_argument(\"--i-file\",
          dest=\"i_file\", type=str, required=True, default=argparse.SUPPRESS)\n_parsed_args
          = vars(_parser.parse_args())\n\n_outputs = read_csv(**_parsed_args)\n"],
          "image": "python:3.7"}}, "inputs": [{"name": "i_file"}], "name": "Read csv"}',
        pipelines.kubeflow.org/component_ref: '{"digest": "8cc454965c0ee7ba1f52867d8b06fb4f41c6ecf74b9b7e6f873c6064885d0905",
          "url": "https://raw.githubusercontent.com/terus-lim-df/kubeflow-pipeline/main/sample1__embulk_component.yaml"}',
        pipelines.kubeflow.org/arguments.parameters: '{"i_file": "{{inputs.parameters.file_path}}"}'}
  arguments:
    parameters:
    - {name: file_path}
  serviceAccountName: pipeline-runner
